services:
  - type: web
    name: checkcheats-server
    runtime: node
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_TIMEOUT
        value: 3600000
      - key: DB_PATH
        value: /opt/render/project/src/checkcheats.db
